### ISSUE TITLE
Add canonical URL 

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#111]
In #85 we added content copy/pasted from https://developer.lightbend.com/docs/introduction/traditional-architecture.html. The page https://github.com/akka/akka-platform-guide/blame/main/docs-source/docs/modules/concepts/pages/concepts-traditional-architecture.adoc should include a `canonical` tag pointing to the page in `https://developer.lightbend.com...`.

**Comment by patriknw** [comment]
Does that mean that if ppl google it they will end up at the developer.lightbend page?

**Comment by ignasi35** [comment]
> Does that mean that if ppl google it they will end up at the developer.lightbend page?

Ah, ofc! I guess we should consider adding the canonical in `https://developer.lightbend.com` to point to `https://guide.akka.io/...` (that is, _here_).

**Comment by ignasi35** [comment]
@jtownley, we probably want to review https://developer.lightbend.com/docs/introduction/planning/microservices-project.html and https://developer.lightbend.com/docs/introduction/traditional-architecture.html to edit/remove(?) them and promote the contents _here_. WDYT?

**Comment by patriknw** [comment]
Thanks. I think we will get back to this when we know more concretely what the overlap will be.

**Comment by ignasi35** [comment]
> I think this falls into the "How" side of the process and I am very happy with the execution of these types of decisions being development ones.
> If your looking for general opinion I think having 1 place only for documentation would be good. If its cross project developer.lightbend.com seems good.
> If you are concerned that there is a business driver here that I might be missing let me know.

@jtownley the problem with https://developer.lightbend.com/docs/introduction/ is that it contains docs for multiple products across the Lightbend Stack (some of which fall out of the Akka Platform Guide scope). IMHO, we should move anything that's specific to the Akka Platform to the new Guide we're putting together, but doing that will make the contents of https://developer.lightbend.com/docs/introduction very scarce. My main concern is finding the owner for that set of docs(https://developer.lightbend.com/docs/introduction/) so we can decide a plan for it.

**Comment by patriknw** [comment]
The guide will be published at developer.lightbend.com. Let's address any overlap between the introduction and the guide in another ticket (updating the introduction).
