### ISSUE TITLE
Use of Cassandra

### ISSUE THREAD

**Issue by chbatey** [akka/akka-platform-guide#118]
Opening up the discussion as to whether Cassandra should be our default store for a new guide. 

Reasons why I think we should consider using JDBC instead:
* We aren't doing a tutorial for a multi-dc app, Cassandra's main use case
* Avoiding giving the impression to use Akka for event sourcing/CQRS you need to use Cassandra
* Understanding eventual consistency delay (I think this makes Couchbase/Cassandra much harder to work with than Spanner/JDBC)

What's the downside of using JDBC for a single DC app? Throughput? Do we have an idea of how many events/s we'd consider a good time to consider Cassandra instead?

**Comment by patriknw** [comment]
Good question for Product.

In the end I think we should have both. The nice thing is that it's not very much that will be different. It's mainly ItemPopularityProjection.

**Comment by patriknw** [comment]
Done
