### ISSUE TITLE
[CSS] Alignment and style of blockquotes

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#120]
While inserting a quote from the Reactive Manifesto I used the syntax for [blockquotes](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#more-delimited-blocks) which, by default, renders to something similar to:

<img width="756" alt="Screenshot 2020-08-27 at 17 37 27" src="https://user-images.githubusercontent.com/762126/91463829-24483980-e88c-11ea-8a56-ed25b274f3c9.png">

The Lightbend/Akka theme could use a couple of improvements to better align with the default:

1. a clear quote indicator (Currently, the theme only tabs the content. It doesn't use an icon, italics, or different font.)
2. right-alignment of the author and reference.

See the following example rendered using the Lightbend theme:

<img width="766" alt="Screenshot 2020-08-27 at 17 40 02" src="https://user-images.githubusercontent.com/762126/91464002-5f4a6d00-e88c-11ea-9426-a5235172681c.png">

**Comment by patriknw** [comment]
@ignasi35 do you know if this has been done?

**Comment by ignasi35** [comment]
<img width="948" alt="Screenshot 2020-11-06 at 10 55 34" src="https://user-images.githubusercontent.com/762126/98352782-c455d800-201e-11eb-9b24-0427b43227db.png">


The new look is a bit clearer that the highlight is a quote. I think it's good enough.
