### ISSUE TITLE
Use project/Dependencies.scala in examples?

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#124]
https://github.com/akka/akka-microservices-seed.g8/pull/1/files#r479092903

I'm not sure. Keeping everything in one single build.sbt is also nice.

**Comment by chbatey** [comment]
I think it is just style preference which you prefer so i'd lean towards sticking with what we've got

**Comment by patriknw** [comment]
Closing, until there is a strong argument about why a split build would be better for these applications
