### ISSUE TITLE
[EPIC] Connect tutorial to concepts

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#138]
> API documentation should therefore provide background knowledge to facilitate entry into an API for developers without prior experience in the domain covered by the API.

**Comment by patriknw** [comment]
Good example of highlighting relevant concepts: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

**Comment by patriknw** [comment]
Several were added. Not sure if more are needed, but closing for this first pass and we can see if we get any feedback.
