### ISSUE TITLE
[Concept or HowTo] Consumer-only services

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#154]
There's a common pattern in microservices where a microservice doesn't expose any blocking endpoint (HTTP/gRPC) and, instead only consumes broker topics and emits data into other brokers or storages.

Refs: https://github.com/lagom/lagom/issues/1288
Refs: https://www.lagomframework.com/documentation/current/scala/KafkaClient.html#Subscriber-only-Services

**Comment by patriknw** [comment]
Yes. How is this different from other optional pieces, such as a service without projections? The g8 template comes with all dependencies but no code to start any of the pieces. Then dependencies can be optimized depending on usage #51

**Comment by patriknw** [comment]
We can indeed have something describing that not all pieces from the tutorial are mandatory.

**Comment by ignasi35** [comment]
> Yes. How is this different from other optional pieces, such as a service without projections?

As I was working on #155 I added a mention to `consumer only service` but did not go into detail regarding what it is. I think adding a couple of paragraphs with a high-level explanation and steps to create a service like that (1. use the g8, 2. cleanup the build using that howto, 3. enjoy) could be useful.

**Comment by ignasi35** [comment]
Refs #156 aswell.

**Comment by ignasi35** [comment]
Discussed in #164. We'll keep this as a mention, not even a section on a concepts page.
