### ISSUE TITLE
[Howto] Use ServiceDiscovery for Kafka and Cassandra

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#157]
In the tutorial, both Kafka and Cassandra clients use either default values or hardcoded `host:port` values.

A new how-to on migrating away from hardcoded values in favor of service discovery would be useful.

**Comment by patriknw** [comment]
no, we consciously changed from service discovery https://github.com/akka/akka-platform-guide/pull/92

**Comment by ignasi35** [comment]
> no, we consciously changed from service discovery #92

Sure, explaining how to use Service Discovery for Kafka and Cassandra is not necessary for neither local development nor kubernetes deployment, but it may be in other targets. I just want to increase the visibility of the feature.
I'm all in favor of keeping the tutorial (including the deployment steps) as simple as possible.

**Comment by patriknw** [comment]
The goal of the guide is not to explain all possible ways of doing thing, but **the way** of doing it for Kubernetes (the cloud).
