### ISSUE TITLE
add more code callouts

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#174]
I added to grpc-server in https://github.com/akka/akka-platform-guide/pull/173 and we can add more to other pages.

Suggested by @WadeWaldron

**Comment by octonato** [comment]
One something that we can add in a callout is when we complete the entity. In that step, we add a boolean to the `Summary` reflecting if the cart is checked out or not. 

There is no mention of this in the tutorial. A callout will be useful here.

**Comment by thothmoses** [comment]
This has been added here:
https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/complete-entity.html#_add_new_operations_to_the_service_descriptor
