### ISSUE TITLE
Don't create keyspace and tables automatically

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#18]
The `Main` of the sample is now creating keyspace and tables automatically, which is not our recommendation for production. Ok to do that from tests.

How should we deal with this for running locally? Easy of running vs the right thing for production?

**Comment by patriknw** [comment]
@ennru suggested that this might be possible from docker compose

**Comment by chbatey** [comment]
I don't think docker compose supports this, recommendations suggest editing the entrypoint/command of the image, which we don't want to do as we're using standard kafka/cassandra images.

We could provide a script that executes docker-compose and then waits for them to be up and then creates the schema. WDYT?

**Comment by ennru** [comment]
> We could provide a script that executes docker-compose and then waits for them to be up and then creates the schema. 

SGTM. It should have the CQL in a separate file so we can reuse the script in other examples.

**Comment by patriknw** [comment]
@chbatey killrvideo example has something https://github.com/KillrVideo/killrvideo-dse-config

**Comment by chbatey** [comment]
That builds a new image that does it. I assume we want to use the standard
image

**Comment by octonato** [comment]
A script will require the user to have `cqlsh` installed, no? 

We can avoid it with a minimal image packaging the scripts and starting as a side-cart to the cassandra container. We let docker-compose pick it as well. 

The side-cart can then create the schema. For the users there is only one thing to do, start the he docker compose.

**Comment by octonato** [comment]
For clarify, I'm using the term side-cart, but I'm not suggesting a side-cart in k8s. Just a container in docker-compose to do some scripting and configuring the other containers.

**Comment by patriknw** [comment]
I think `cqlsh` is available in the Cassandra with docker-compose, then the user can run the script with `docker run`.
Something similar to what is in https://doc.akka.io/docs/akka-projection/current/getting-started/running.html#running-the-projection

**Comment by octonato** [comment]
I'm afraid this will be annoying to do repeatedly. 

First, the docker containers are prepended with the name of the current folder. And that also impact the name of the docker network to use. For instance, I just created a new seed in a folder called `demo`. 

I have the following containers:

```
demo_cassandra_1    Up About a minute   7000-7001/tcp, 7199/tcp, 9160/tcp, 0.0.0.0:9042->9042/tcp
demo_zookeeper_1    Up About a minute   22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp
demo_kafka_1        Up About a minute   0.0.0.0:9092->9092/tcp
```

The network to use in that case is `demo_default`. Btw, I had to look out how to find the network name. We will need to document it how to find the right network.

Now I can call: 

```
docker run -it --network demo_default --rm cassandra cqlsh cassandra
```

But I can't pass a file to `cqlsh`. I get a "the input device is not a TTY" error message. 
It's maybe possible, but need to find out how. And we will need to document it to users as well. 

I have to start it and copy-n-paste the create table statements, but first I need to open the file somewhere and put it on my clipboard. 

Then tomorrow I want to drop my container and start from scratch. Now I have to go through it again. 

For a better getting start experience, I think it should be one command (or maybe two), but fully automated so users can setup everything without much ado. 

Of course, this puts the burden on us to maintain whatever we put in place to facilitate it.

**Comment by ennru** [comment]
We have several examples in Alpakka's docker-compose that create a preparations container which will configure the main container. That would work here as well.

**Comment by patriknw** [comment]
This works:
```
docker exec -i shopping-cart-service-scala_cassandra_1 cqlsh -t < src/main/resources/create_tables.cql
```
see explanation at https://stackoverflow.com/questions/53951136/pass-file-content-to-docker-exec/53951197

Having an image seems too heavy and the cql script must anyway be outside the image so that it can be customized.

We could have a script for the two commands, but probably best to just start with documenting them.

**Comment by johanandren** [comment]
Related #218

**Comment by octonato** [comment]
I will go for documenting how to load the script from `src/main/resources`

> Having an image seems too heavy and the cql script must anyway be outside the image so that it can be customized.

For the record, my idea was not to publish a container with the script, but let docker-compose built a image on the fly and include the script from `src/main/resources`, but there is a catch on this. Once the image is built, it will re-use it on the second run. If you change the script, you need to delete your image. 

Letting the user load the script is indeed better.
