### ISSUE TITLE
Standardize footer

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#181]
Some pages use the footer:

```
 **This documentation was last published: {localdate}**
```

We should create a `partial` for it and include it everywhere.

**Comment by patriknw** [comment]
wouldn't that be part of the style https://github.com/akka/akka-platform-guide/issues/3 ?

**Comment by ignasi35** [comment]
> wouldn't that be part of the style #3 ?

Yeah, the theme can probably handle that.

**Comment by ignasi35** [comment]
See also #268

**Comment by patriknw** [comment]
I think this has been discussed and can be closed.
