### ISSUE TITLE
Review NAV depth and contents

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#185]
See discussion at https://github.com/akka/akka-platform-guide/pull/177#discussion_r486313550:

> I'm a bit undecided about what should the nav look like:
> 
> a) too detailed becomes noisy and messy: detailed concepts mixed with tutorial steps. As content grows, this alternative make snavigation too difficult aswell.
> b) too scarce makes navigation more difficult

**Comment by patriknw** [comment]
I think this is handled by https://github.com/akka/akka-platform-guide/pull/343 for now. We might have to revisit when adding more How to, but that will probably be handled by not showing all those in nave but in an index page instead.
