### ISSUE TITLE
[cosmetic/UX] The nav Div hides the section title

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#197]
While browsing from a narrow viewport (e.g. mobile phone) the nav div is not on the left but as a floating div at the top (under the orange header).

When clicking on a link that includes and anchor id, the content scrolls too much and the section title is hidden behind the nav div.

Expected:

![Screenshot_20200911-171412.jpg](https://user-images.githubusercontent.com/762126/92943139-afabf800-f452-11ea-9971-452c8c591743.jpg)

Actual:

![Screenshot_20200911-171404.jpg](https://user-images.githubusercontent.com/762126/92943148-b2a6e880-f452-11ea-86ad-e6823156c403.jpg)

**Comment by patriknw** [comment]
@ignasi35 Can you confirm if this has been fixed? I don't know what to look for.

**Comment by ignasi35** [comment]
This is fixed. 👍🏼
