### ISSUE TITLE
Split up the Scala example code in parts

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#199]
Steps `01` and `02` (in https://github.com/akka/akka-platform-guide/blob/main/docs-source/docs/modules/microservices-tutorial/examples/) don't include a `build.sbt` and other project files.

**Comment by patriknw** [comment]
Split in one directory for each part in the tutorial. Each should be a self contained and complete project that can be built and run. That is needed for the downloads https://github.com/akka/akka-platform-guide/issues/61

Some snippets in the tutorial should also be updated to include code from the right part.

**Comment by patriknw** [comment]
Many files will be identical copies in several places and for those we could create a script to copy them from the full example.

**Comment by ignasi35** [comment]
done in #225
