### ISSUE TITLE
adjust scalafmt settings to avoid horizontal scroll

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#207]
When we have the final style https://github.com/akka/akka-platform-guide/issues/3

**Comment by ignasi35** [comment]
In My machine, using a maximized browser, the divs for snippets show up to 98 columns of monospaced code.
(of course, decreasing the the browser width, the number of viewable columns also decreases)

**Comment by ennru** [comment]
Fixed for Scala with #285
