### ISSUE TITLE
Introduce the reactive principles

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#211]
The section in `concepts` regarding properties of a reactive microsystem may include a small reference to https://principles.reactive.foundation/principles/index.html

Other concepts may also refer to https://principles.reactive.foundation/principles/index.html, e.g.: when introducing supervision, mention how that is part of embracing failure (principle III).

**Comment by patriknw** [comment]
Links were added. Let's start with that and we can revisit later if we want more.
