### ISSUE TITLE
Wrong ActorSystem name in Part 3: First gRPC service

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#214]
`ActorSystem[Nothing](Main(), "Cart")` should be `ActorSystem[Nothing](Main(), "ShoppingCartService")`

**Comment by ignasi35** [comment]
IIUC, this change is for cluster bootstrap. How about introducing:

```
akka.management {
  cluster.bootstrap {
    contact-point-discovery {
      ...
      service-name = "shoppingcartservice"
    }
  }
}
```

in the settings and decouple the deployment from the actor system name.

**Comment by patriknw** [comment]
We can do that to connect the dots more explicitly. We should still update the ActorSystem name, since I don't think it's matching what the seed generated.
