### ISSUE TITLE
Missing tables when running shopping-cart-service-scala

### ISSUE THREAD

**Issue by johanandren** [akka/akka-platform-guide#218]
Looks like the cassandra tables are never actually created:

```
[2020-09-30 14:49:24,098] [WARN] [akka.stream.scaladsl.RestartWithBackoffSource] [akka://ShoppingCartService@127.0.0.1:2551] [] [ShoppingCartService-akka.actor.default-dispatcher-15] - Restarting graph due to failure. stack_trace:
com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: unconfigured table tag_views
```

**Comment by patriknw** [comment]
I think it will work next time you start it. Some race when starting up. One of the reasons we want don't want to create them automatically.

**Comment by johanandren** [comment]
Single cluster node, so shouldn't be race between nodes AFAICS. It has failed consistently over several docker-compose stop remove restarts.

I guess there is no need to dig into this if we intend to do the creation some other way anyway. Kind of makes it hard to verify that the integration tests actually work though.

**Comment by patriknw** [comment]
You mean that this is from a test? Not from `run`? I haven't seen that problem in the Scala tests. For tests we want to create the keyspace/tables automatically. Unique name of the keyspace to not interfere with local run or other tests.

**Comment by johanandren** [comment]
I see it both from run and from testOnly with the projeciton integration test I was porting.

**Comment by patriknw** [comment]
Run should be covered with the new instructions for docker and cql script that has been merged.

Could you point me to the integration spec that is failing?

**Comment by johanandren** [comment]
NVM, seems to work now that I tried.
