### ISSUE TITLE
[Style] Prefer "learn more" over "see also"

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#235]
In all types of pages (tutorials, concepts, etc...) we often add a final note with more resources to extend the concepts. We're using `Learn more` and `see also` inconsistently.

Prefer `Learn more`.

**Comment by octonato** [comment]
I did a quick test using admonitions and didn't work as expected. We can still see if we can have some style for the Learn More section. Probably something to be added to the Lightbend theme. 

(cc rasummer)

**Comment by ignasi35** [comment]
> I did a quick test using admonitions and didn't work as expected. We can still see if we can have some style for the Learn More section. Probably something to be added to the Lightbend theme.

Maybe we can have a CSS class we would then use via AsciiDoc [roles][(https://asciidoctor.org/docs/user-manual/#role).

**Comment by ennru** [comment]
I fixed the existing deviations in #286. A style would be nice but we can live without.

**Comment by rasummer** [comment]
I can add a Learn More style that works like 'Tip' or 'Note' and has a little icon etc

**Comment by patriknw** [comment]
@rasummer That would be great, thanks.

**Comment by ignasi35** [comment]
@rasummer I think we may even work without that new style.

In https://github.com/akka/akka-platform-guide/pull/296#discussion_r504777584 @octonato used a type of block that I think looks quite neat.

It may be useful to use the same type of block for "Download source code" and "Learn more" since both are _optional_ contents you can do without.

**Comment by ignasi35** [comment]
> It may be useful to use the same type of block for "Download source code" and "Learn more" since both are _optional_ contents you can do without.

@rstento what do you think about this idea 👆🏼

**Comment by patriknw** [comment]
The content change is done, but keeping it open until the styling is completed.

**Comment by patriknw** [comment]
> I can add a Learn More style that works like 'Tip' or 'Note' and has a little icon etc

@rasummer is this something that you are working on?

**Comment by rasummer** [comment]
> @rasummer I think we may even work without that new style.
> 
> In [#296 (comment)](https://github.com/akka/akka-platform-guide/pull/296#discussion_r504777584) @octonato used a type of block that I think looks quite neat.
> 
> It may be useful to use the same type of block for "Download source code" and "Learn more" since both are _optional_ contents you can do without.

@patriknw I put this one on the hold as it sounded like the team was going to use [sidebar blocks](https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/build/site/sidebar-blocks.html) for the Learn More sections.

**Comment by patriknw** [comment]
ok, works for me. Created https://github.com/akka/akka-platform-guide/issues/393 for that task.
