### ISSUE TITLE
[concepts] Akka modules

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#249]
The concepts section has scaffolding for all the akka modules used in the microservices tutorials:

- [x] akka core (actors) #260 
- [x] akka streams #244 
- [x] akka cluster #261 
- [x] akka persistence #262
- [x] akka projections #263 
- [x] akka management #234

**Comment by patriknw** [comment]
Maybe we can steal some summaries from https://doc.akka.io/docs/akka/current/typed/guide/modules.html

**Comment by ennru** [comment]
They are all filled in and merged now.
