### ISSUE TITLE
how to: scale write-side and read-side independent of each other

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#25]
I don't think "write-model" and "read-model" are great names for the roles.

"write-side" and "read-side" are slightly better. A projection reads the events. Entities writes the events.

"entity" and "projection" might be better?

Also, define constants in the code for these roles.

**Comment by patriknw** [comment]
and when updating to Akka 2.6.9 we can use `ShardedDaemonProcessSettings.withRole` https://github.com/akka/akka/issues/29490

**Comment by patriknw** [comment]
Second thought: We can simplify the sample by not using roles at first, and then have a "how to scale write-side and read-side independent of each other"

**Comment by ignasi35** [comment]
> "entity" and "projection" might be better?

+1 to that. Or even `eventsourcing` and `projections`. And a hint that each projection may use a dedicated role for more fine-grained control.
