### ISSUE TITLE
[style] Links to contents under akka.io are not external

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#253]
We use the `tab-icon` double-link trick for any link that's not in the platform guide directly.

This is not 100% correct since we often link to contents under akka.io which should not be considered external either. For example:

```
{akka-management}[Akka Management] {akka-management}[{tab-icon}, window="tab"]
```

Should be:

```
{akka-management}[Akka Management]
```

**Comment by ennru** [comment]
The guide lives on lightbend.com now so akka.io are external.
