### ISSUE TITLE
Include Java code in tutorial

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#258]
include snippets to be shown as separate Scala/Java tabs

Some text content should also be adjusted based on the choice. I don't know if there is a solution for this yet or if we have to develop some Antora addition?

**Comment by johanandren** [comment]
I've tried to keep the include tags to correspond with the Scala ones in #213 but it will surely need work through to check that it is ok.

**Comment by patriknw** [comment]
I never started this. Open for grabs.
