### ISSUE TITLE
Publish at developer.lightbend.com

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#264]
The decision is that the guide should be at developer.lightbend.com

We need to find a way to publish it from CI.

**Comment by patriknw** [comment]
@RayRoestenburg Do you have some pointers to how the Cloudflow Enterprise docs are published?
https://developer.lightbend.com/docs/cloudflow/current/index.html

**Comment by RayRoestenburg** [comment]
@patriknw https://github.com/lightbend/cloudflow-enterprise-docs

**Comment by patriknw** [comment]
I think this is done

**Comment by ennru** [comment]
https://github.com/lightbend/techhub/pull/352 removes it from TechHub again until we have a decision about publishing.

When we start publishing, the TechHub URL ping must be added.
