### ISSUE TITLE
Detect broken links

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#265]
We should have an automated mechanism to detect broken links.

Here's a mistake I make often: I declare `:foo:  http://com.com/` and use `{foo}/subpath` which renders `http://com.com//path`.

**Comment by ennru** [comment]
The link checker `make check-link` now works. Let's create a scheduled task to verify links.

Refs #283

**Comment by ennru** [comment]
This is what my home-grown link checker thinks about the current status in `main`:

## Non-HTTP OK pages
https://developer.lightbend.com/docs/akka-platform-guide status 404 Not Found
 - concepts/akka-actor.html
 - concepts/akka-management.html
 - ... 41 more

https://doc.akka.io/docs/akka/current/split-brain-resolver status 404 Not Found
 - concepts/akka-management.html

https://www.reactivemanifesto.org//glossary status 404 Not Found
 - concepts/reactive-streams.html

https://www.amazon.com/Domain-Driven-Design-Distilled-Vaughn-Vernon-ebook/dp/B01JJSGE5S/ref=sr_1_1?dchild=1&keywords=Domain-Driven+Design+Distilled&qid=1599820686&s=books&sr=1-1 status 405 Method Not Allowed
 - concepts/ddd.html

https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215/ref=sr_1_1?dchild=1&keywords=Domain-Driven+Design&qid=1599820577&s=books&sr=1-1 status 405 Method Not Allowed
 - concepts/ddd.html


## Redirected URLs
https://principles.reactive.foundation/principles should be
http://principles.reactive.foundation/principles/
 - concepts/isolation.html

https://portal.lightbend.com/ should be
/account/login
 - concepts/akka-actor.html
 - concepts/akka-management.html
 - ... 41 more

**Comment by ignasi35** [comment]
```
## Redirected URLs
https://principles.reactive.foundation/principles should be
http://principles.reactive.foundation/principles/
```

Hmm, I get the trailing `/` but default to http?

**Comment by ennru** [comment]
> Hmm, I get the trailing / but default to http?

My browser doesn't change to http. Must be something in my tool.

**Comment by ignasi35** [comment]
> My browser doesn't change to http. Must be something in my tool.

It's a double redirect:

```
$ curl -v https://principles.reactive.foundation/principles
*   Trying 216.239.38.21...
* TCP_NODELAY set
...
* Using Stream ID: 1 (easy handle 0x7fd42f80c400)
> GET /principles HTTP/2
> Host: principles.reactive.foundation
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< content-type: text/html
< location: http://principles.reactive.foundation/principles/
< x-cloud-trace-context: 94d655e92e160cf7c48d5e4d1d9f7682;o=1
< date: Fri, 16 Oct 2020 13:03:55 GMT
< server: Google Frontend
< content-length: 169
<
<html>
...
</html>
* Connection #0 to host principles.reactive.foundation left intact
* Closing connection 0


$ curl -v http://principles.reactive.foundation/principles/
*   Trying 216.239.38.21...
* TCP_NODELAY set
* Connected to principles.reactive.foundation (216.239.38.21) port 80 (#0)
> GET /principles/ HTTP/1.1
> Host: principles.reactive.foundation
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Location: https://principles.reactive.foundation/principles/
< X-Cloud-Trace-Context: 491314df77bcec8cf765c59d98d6b7c2
< Date: Fri, 16 Oct 2020 13:04:12 GMT
< Content-Type: text/html
< Server: Google Frontend
< Content-Length: 0
<
* Connection #0 to host principles.reactive.foundation left intact
* Closing connection 0
```

**Comment by ennru** [comment]
Yes, that's what I thought. So they should actually fix it in their redirects.

**Comment by patriknw** [comment]
This is done by https://github.com/akka/akka-platform-guide/pull/319, I assume
