### ISSUE TITLE
Use admonition blocks for "Learn More" section

### ISSUE THREAD

**Issue by octonato** [akka/akka-platform-guide#267]
I would say that's out-of-scope for now, but ticktifying so we can discuss the benefits and eventually do it later. 

Based on comment here: https://github.com/akka/akka-platform-guide/pull/261#discussion_r501216862_

**Comment by ignasi35** [comment]
related to #235 

I think the list of supported admonitions in asciidoc is a closed set. The docs in Antora and asciidoc are a bit ambiguous, though. See https://docs.antora.org/antora/2.3/asciidoc/admonitions/
