### ISSUE TITLE
[Syntax/Style] Links to external content

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#270]
In #266 there's a mix in link styles:

1. `https://www.som-url.com/[IntelliJ IDEA] https://www.som-url.com/[{tab-icon}, window="tab"]` (two links, duplicate URL)
2. `https://www.som-url.com/[IntelliJ IDEA {tab-icon}, window="tab"]` (single link)

There's also a case or two where `window="tab"` is replaced with `window="new"`.

The rules for when to use two links VS one link or when to use `tab` VS `new` are unclear to me.

I think there may be a way to simplify all this and defer to some antora-theme magic so we don't need to remeber such rules every time.

**Comment by patriknw** [comment]
"tab" or "new" doesn't matter so we should just use the same.

@rstento what was the conclusion regarding the external link syntax? Can we remove the duplicate url?
I can't see that it is rendered differently or behave differently.

Concrete example in dev-env.adoc
```
https://docs.docker.com[Docker {tab-icon}, window="tab"]. The template project's root directory includes a
https://docs.docker.com/compose/[Docker Compose] https://docs.docker.com/compose/[{tab-icon}, window="tab"]
```

**Comment by patriknw** [comment]
There is also a 3rd variant that has two separate links
```
{akka}/typed/cluster-singleton.html#lease[Akka Cluster Singleton] {akka}/typed/cluster-singleton.html#lease[{tab-icon}, window="tab"]
```

That is very confusing. External links should only open in separate tab/window.

**Comment by rstento** [comment]
Agreed that external links should only open in a separate tab/window. The
double link where clicking the link opens in the same tab and clicking the
icon opens in a different one was requested by one of my reviewers on the
Reactive Principles site. I did it, but later found that it is easy to
click the wrong place and have the opposite behavior of what you expected.
The simpler model of having them all behave the same when they have the
outward arrow icon is better.
