### ISSUE TITLE
Validate Antora links

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#283]
#282 enabled the link checker. 

Unfortunately we have no tooling to validate Antora `xref`:

```
I _know_ there is a broken link on `ROOT/pages/index.adoc`, though. I guess the link checker will only validate asciidoc and markdown links but not antora references.

This is not a blocker to merge this PR but something we should look into on a separate PR.


PS. the error is on `concepts` (https://github.com/akka/akka-platform-guide/blame/main/docs-source/docs/modules/ROOT/pages/index.adoc#L16) that has un colon `:` too many.
```

_Originally posted by @ignasi35 in https://github.com/akka/akka-platform-guide/pull/282#issuecomment-707631124_

**Comment by ennru** [comment]
#409 added a link checker which runs via a GitHub workflow.

**Comment by ennru** [comment]
The link checker seems to work well now https://github.com/akka/akka-platform-guide/actions?query=workflow%3A%22Link+Validator%22
