### ISSUE TITLE
Enable Akka design on the site

### ISSUE THREAD

**Issue by ennru** [akka/akka-platform-guide#3]
I've initiated work to get an Akka design for Antora.

**Comment by patriknw** [comment]
For information in case others have same problem: For unknown reason the Lightbend style didn't show up in Safari for me. Works in Chrome.

**Comment by patriknw** [comment]
Related https://github.com/akka/akka-platform-guide/issues/91

**Comment by patriknw** [comment]
This is in progress

**Comment by ennru** [comment]
Fixed with #268
