### ISSUE TITLE
Seed projects for Java examples

### ISSUE THREAD

**Issue by octonato** [akka/akka-platform-guide#305]
As we move forward with the Java examples, we will need seed projects for the order and analytics services. 

The Scala guide recommends to start a new one using `sbt new`, but we don't have such an option for Java. 

Maybe the best option here is to have a zip with the seed for all three projects and for all language and we stop to suggest `sbt new`. 

That will also allow us to remove the instructions to tweak the ports each time.

**Comment by patriknw** [comment]
The tooling for the final templating is not decided so we we need a simple intermediate solution.

For Java I was thinking that we would use a zip (with all 3 empty services) as seed.

For Scala I was thinking that we could keep `sbt new`, but sure, we can remove it and only use zip seed if we think it's too much work to keep the `sbt new` around.

**Comment by octonato** [comment]
I prefer `sbt new` as well, but considering that we now have to maintain two approaches and, in addition to that, we need to ask users to change the ports, it feels awkward. 

Morever, for the first step we say: use `sbt new` or download the seed. Then later, we say: now use `sbt new`, no zip for this step. Sounds also weird.

**Comment by patriknw** [comment]
ok, I'm fine with removing `sbt new` until we know more.

**Comment by patriknw** [comment]
I'll change to 00 zip downloads for Scala.
