### ISSUE TITLE
Broken style

### ISSUE THREAD

**Issue by octonato** [akka/akka-platform-guide#317]
Something went wrong recently. Styling is broken for this section. I remember that this was displaying correctly. 

https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/entity.html#_run

![CleanShot 2020-10-16 at 14 07 26](https://user-images.githubusercontent.com/502982/96256684-66067e00-0fb9-11eb-90ed-2698c053cd44.png)

@rasummer, I'm not sure if that is due to theme changes or because we are using `+` to indent the content.

**Comment by rasummer** [comment]
The CSS changes I made yesterday were mostly limited to some background colors and styling the sidebar. Assuming all content needs to be indented under `#2` and using the `+` symbol to keep it all together? I'll take a look today.

**Comment by octonato** [comment]
Yes, that's what I think it was the intention. All indented under #2. 

It may be some unforeseen combination that is causing it. The original commit, that was displaying correctly, didn't have the indentation.

**Comment by rasummer** [comment]
My guess is it's a Asciidoc syntax issue, I will take a look regardless.
