### ISSUE TITLE
[CSS] Font size for code blocks too big

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#362]
(this is a personal opinion)

I find the font size (currently 16px) of code block too big. Reducing it to 14px the result is still very readable and we remove the horizontal scrolling from Java code (we would then be able to increase the line witdh restrictions in scala code too).

Some examples:

**BEFORE**

<img width="899" alt="Screenshot 2020-10-23 at 10 19 36" src="https://user-images.githubusercontent.com/762126/96974307-55a25600-1519-11eb-97f1-9bbe1adfd2e8.png">

**AFTER** 

<img width="958" alt="Screenshot 2020-10-23 at 10 18 59" src="https://user-images.githubusercontent.com/762126/96974370-6f439d80-1519-11eb-8d60-83e40bbe3595.png">

------------------

**BEFORE** 

<img width="973" alt="Screenshot 2020-10-23 at 10 19 46" src="https://user-images.githubusercontent.com/762126/96974319-589d4680-1519-11eb-987e-802f45070f28.png">

**AFTER** 

<img width="951" alt="Screenshot 2020-10-23 at 10 19 09" src="https://user-images.githubusercontent.com/762126/96974382-723e8e00-1519-11eb-8893-98f4f187711d.png">

**Comment by ignasi35** [comment]
cc @rasummer

**Comment by patriknw** [comment]
I agree and was about to suggest same. Currently we have formatted the Scala code with an insane small line width. We must change that and decreasing the font will give us some additional chars.

@ignasi35 If yo know where to change the font right now in akka-platform-guide that would be great so that we can make it look decent today.

**Comment by ignasi35** [comment]
> @ignasi35 If yo know where to change the font right now in akka-platform-guide that would be great so that we can make it look decent today.

I did have a look but in `akka-platform-guide` we only have the minified version of files. (CSS and other stuff).

See discussion in https://github.com/akka/akka-platform-guide/pull/268#issuecomment-705665195

I'll have a look at the actual sources in the main styles repo and PR there...

**Comment by patriknw** [comment]
@rasummer Has this been fixed? I see that it was merged upstream but do we need to change something here?

I think it's looking good, but just wanted to confirm before closing this ticket.

<img width="1639" alt="Screenshot 2020-11-06 at 08 59 47" src="https://user-images.githubusercontent.com/336161/98340986-78029c00-200e-11eb-8cb3-8c60b162bbde.png">

**Comment by rasummer** [comment]
Yes we can close this one.

**Comment by patriknw** [comment]
thanks
