### ISSUE TITLE
Use asciidoc `source` metadata to inform of each snippet location

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#363]
As discussed in #227 it'd be useful is every snippet included the asciidoc metadata re the file location:

```
[source]
.path/to/file
----
```

This also requires a new CSS style (see https://github.com/akka/akka-platform-guide/pull/227#issuecomment-705687263)

**Comment by patriknw** [comment]
File names have been added for appropriate snippets with syntax like:
```
[.tabset]
Java::
+
.src/main/java/shopping/cart/ShoppingCartServiceImpl.java:
[source,java,indent=0]
----
include::example$02-shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCartServiceImpl.java[]
----
```

Some better looking style would be welcome.

However, I'm not convinced we should add this automatically on all snippets. In many cases the snippets continues with existing/same file and then that would just add noise.

**Comment by ignasi35** [comment]
> However, I'm not convinced we should add this automatically on all snippets. In many cases the snippets continues with existing/same file and then that would just add noise.

👍🏼 Let's keep the _rule_ to add the source path as a recommendation instead of a hard requirement.

**Comment by patriknw** [comment]
done, by manually adding it at appropriate places
