### ISSUE TITLE
Source code colouring

### ISSUE THREAD

**Issue by ennru** [akka/akka-platform-guide#383]
The current colouring of the source code snippets is very gray and makes focuses a bit too much on keywords IMHO.
The earlier style had more colour as the screenshots in https://github.com/akka/akka-platform-guide/issues/362 show.

Was this an intentional change @rasummer?

**Comment by rasummer** [comment]
I believe I only changed the font size in my latest PR that made the source code font size smaller. I take a look.

**Comment by rasummer** [comment]
The colors appear to still be styling from the vendor HightlightJS style sheet. See: https://github.com/lightbend/antora-supplemental-ui-lightbend-theme/blob/master/supplemental_ui/css/src/vendor/highlight.css

I don't believe this file hasn't changed as it's a vendor file, and I avoid changing these. 

When looking at it locally, the Scala code (see below) looks the same as the screenshots from #362 

![screenshot-localhost_8000-2020 10 27-15_34_41](https://user-images.githubusercontent.com/1418129/97369465-39305180-186a-11eb-8f3c-c1ac0a6c1c9d.png)

Did you look at the code on a different display/monitor?

**Comment by ennru** [comment]
My Firefox seems to disregard the colours:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/458526/97441961-9b03c080-1929-11eb-92e7-10f9e45882a1.png">

But Chrome and Safari show them. 

<img width="420" alt="image" src="https://user-images.githubusercontent.com/458526/97442132-cb4b5f00-1929-11eb-8750-ace1e1649c4c.png">

I don't see an obvous reason, so let's ignore it.

**Comment by rasummer** [comment]
Luckily my Firefox (mac) is showing the colors, so agree ignore it unless others experience it also.

**Comment by ignasi35** [comment]
I see similar results to what @rasummer posted but I think there's still room for some improvement.
I understand this is a bit out of our hands and probably not a top priority.

My perception regarding "this is colored enough" vs "this is dull) changes denending on the snippet and programming language. 

<details>
<summary>Here's some screenshots</summary>

<img width="733" alt="Screenshot 2020-11-03 at 12 45 05" src="https://user-images.githubusercontent.com/762126/97981923-4f429280-1dd3-11eb-87c2-bc44079af916.png">
<img width="763" alt="Screenshot 2020-11-03 at 12 45 11" src="https://user-images.githubusercontent.com/762126/97981930-52d61980-1dd3-11eb-81f5-5218e68ac108.png">
<img width="723" alt="Screenshot 2020-11-03 at 12 47 40" src="https://user-images.githubusercontent.com/762126/97981936-536eb000-1dd3-11eb-97e4-476021f1aca7.png">
<img width="909" alt="Screenshot 2020-11-03 at 12 48 01" src="https://user-images.githubusercontent.com/762126/97981938-54074680-1dd3-11eb-91b3-d22d33247911.png">


</details>

**Comment by rasummer** [comment]
Agree, it would be nice to work on the coloring of code. I will add to my list, but it will be a behind a few other items. Once I do get to it, I'll ping you with some options.

**Comment by ennru** [comment]
Ok, this is nothing we need to put any effort in.
