### ISSUE TITLE
Overview diagram improvements

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#388]
Some suggestions by @jpollock for improving the overview diagram.

* `ask` - Maybe just confusing if someone doesn't know Akka at all.
* Cart Entity should have a different shape, since it's not the same type as other round.
* The Microservice boundaries should be clarified. (currently dashed lines)
* Instead of message broker we could say Kafka to be more specific, since gRPC is specific.

**Comment by jpollock** [comment]
I think that we solve the bigger issues by:

1. Removing the "ask" label.
2. Putting "Microservice" label outside of each of the dashed lined boxes, in smallish font. This clearly indicates that each is in fact a microservice.
3. Reflecting more, I think that I'm good with the message broker. Yes, gRPC is specific but I think that it ends up being perceived differently. I'm 100% fine with the generic message broker image; in fact, I believe that this is the better choice.

**Comment by patriknw** [comment]
What do you think about this?

<img width="1018" alt="Screenshot 2020-11-06 at 10 55 41" src="https://user-images.githubusercontent.com/336161/98352764-bc963380-201e-11eb-8b08-942b6294b89e.png">
