### ISSUE TITLE
Missing zip examples

### ISSUE THREAD

**Issue by sebastian-alfers** [akka/akka-platform-guide#407]
The mentioned files at https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/template.html#_download_the_empty_template are not attached to the link (both Java and Scala).

**Comment by patriknw** [comment]
I think this is what @ennru fixed in https://github.com/akka/akka-platform-guide/pull/398

**Comment by ennru** [comment]
No, I still haven't figured out why that fix didn't do the trick.

**Comment by sebastian-alfers** [comment]
I think the problem is that if we build the site, antora does a clean git-checkout within the docker-container which of course does not have the zips (they are generated on the fly). 

It does work using `make local-preview`.

**Comment by sebastian-alfers** [comment]
I see two options:

1. build the final distribution also with [author-mode](https://docs.antora.org/antora/2.1/playbook/author-mode/) or
2. move the zips manually to the final directory in `target/microservices-tutorial/_attachments`

**Comment by ennru** [comment]
Thank you for looking into it.
I'd prefer solution 2. as `author-mode` is useful with work-in-progress flags and such.
