### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#42]
I would like to suggest that we structure the documentation like Django documentation:
https://docs.djangoproject.com/en/3.1/internals/contributing/writing-documentation/#how-the-documentation-is-organized

* Tutorial - step by step tutorial building up the sample project
* Concepts - general explanation of concepts and motivations
* How to - recipes for specific things (additions to the tutorial sample)
* Reference - overview of links to reference documentation

I know there is an article describing how to structure documentation around these 4 topics, but I can't find it at the moment.

**Comment by ignasi35** [comment]
+1 to this separation with a small comment. 

I would not add the `concepts` section in this repo. Instead, I'd focus this repo into building something incrementally. That is, the Tutorial and the How to's.

**Comment by ignasi35** [comment]
> I would not add the `concepts` section in this repo. Instead, I'd focus this repo into building something incrementally. That is, the Tutorial and the How to's.

I got mislead by the current repo name `akka-microservices-samples`. This is the correct repo.

**Comment by patriknw** [comment]
yeah, we should probably rename the repo, created issue https://github.com/akka/akka-microservices-samples/issues/60

**Comment by ignasi35** [comment]
@patriknw we can probably close this one already, right?

**Comment by patriknw** [comment]
Ruth will look into what we have done so far and this is one thing we want feedback on from her (she knows). Let's keep it open until then.

**Comment by patriknw** [comment]
I think we have confirmed with Ruth that the structure works. I have created https://github.com/akka/akka-platform-guide/issues/179 for follow up on the concepts structure.
