### ISSUE TITLE
Hibernate should not auto-create tables

### ISSUE THREAD

**Issue by octonato** [akka/akka-platform-guide#435]
Even when using `"hibernate.hbm2ddl.auto" = "none"` Hibernate is create the tables in dev/prod mode.

**Comment by patriknw** [comment]
@octonato Did you fix this?

**Comment by octonato** [comment]
nope, I can have a look today while resume the work in the guide

**Comment by patriknw** [comment]
We have `vendorAdapter.setGenerateDdl(true);` in the SpringConfig. Maybe that is wrong?

**Comment by octonato** [comment]
yep, that's was the reason and this is solved in #462
