### ISSUE TITLE
Microservices Tutorial: Possibly missing instruction to add a class

### ISSUE THREAD

**Issue by debasishg** [akka/akka-platform-guide#487]
In the [Projection For Queries](https://akka.io/platform-guide/wip/microservices-tutorial/projection-query.html) in the Platform Guide when we are adding `ItemPopularityRepository` we need to add the class `shopping.cart.ItemPopularity` as well. This instruction is missing.

**Comment by patriknw** [comment]
I think you are right, could you open a PR for this?

**Comment by debasishg** [comment]
Sure .. I will work on it ..
