### ISSUE TITLE
how to: reduce build dependencies

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#51]
Describe what dependencies that can be removed (from the empty template project) when different things are not used.

**Comment by ignasi35** [comment]
Hi @patriknw, this is a rather specific how-to. Other how-to pages will be of use for users with their codebases but this looks too specific for people halfway through the tutorial. I'd rather not add this to the how-to section.

**Comment by patriknw** [comment]
> this looks too specific for people halfway through the tutorial

I don't understand what you mean?

what is "too specific"?

This is option so I don't understand "halfway through the tutorial"?

An example: They create a microservice project that is not using Kafka. We include Kafka dependencies from the g8 template, but this how-to explains that the Kafka dependency can be removed.

**Comment by ignasi35** [comment]
I forgot about the .g8 template.

**Comment by octonato** [comment]
Done in #155
