### ISSUE TITLE
Fargate reference in the Create a Kubernetes cluster section

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#514]
In the "Create a Kubernetes cluster" section of the https://akka.io/platform-guide/wip/deployment/aws-install.html 

There is a note: "We recommend using EKS with EC2 nodes, and not the Fargate option."

This is a bit confusing because there is no mention of where the selection of EC2 or Fargate is made?

**Comment by patriknw** [comment]
Thanks for feedback. It's related to the UI choices. We should make that more clear.
