### ISSUE TITLE
Part V - Add new operations to the service descriptor - instructions are unclear.

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka-platform-guide#537]
### Versions used 

https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/complete-entity.html#_add_new_operations_to_the_service_descriptor

### Actual Behavior

The gRPC service definition being provided isn't clear.

```
service ShoppingCartService {
    rpc Checkout (CheckoutRequest) returns (Cart) {} 
    rpc GetCart (GetCartRequest) returns (Cart) {} 
}
```

When I read this, it seems to imply that I am supposed to either a) replace the existing ShoppingCartService with this new ShoppingCart service, or b) maybe add a second ShoppingCartService. I think what I am actually supposed to do is to take the two rpc calls listed, and insert them into my existing ShoppingCartService. But that's not clear from the instructions.

**Comment by patriknw** [comment]
Thanks
