### ISSUE TITLE
Part VI - No instructions to make required test updates

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka-platform-guide#538]
### Versions used 

https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/projection-query.html#kubernetes

### Expected Behavior

I should be able to compile and run tests.

### Actual Behavior

When attempting to compile and run tests I get the following errors:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project shopping-cart-service: Compilation failure
[ERROR] /Users/wadewaldron/Documents/Lightbend/Training/AkkaPlatformGuide/shopping-cart/shopping-cart-service/src/test/java/shopping/cart/ShoppingCartTest.java:[29,74] method create in class shopping.cart.ShoppingCart cannot be applied to given types;
[ERROR]   required: java.lang.String,java.lang.String
[ERROR]   found: java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length
```

I can bypass this error by adding an arbitrary tag to the creation of the shopping cart in the test.

I have looked through the instructions, and I can't seem to see anywhere that we are told to make this change (or update the tests at all).

**Comment by patriknw** [comment]
That might be an oversight, thanks
