### ISSUE TITLE
CI improvement: manage AWS/GCP with terraform

### ISSUE THREAD

**Issue by chbatey** [akka/akka-platform-guide#545]
Originally brought up by @andreaTP 

If we do this I think we should also start managing users with it as well e.g. the CI service accounts. Right now they are all manually created.

This could also be an opportunity to use a different GCP project for the Akka Operator to make sure there are no conflicts and see billing per project very easily.

**Comment by patriknw** [comment]
wrong repo?

**Comment by chbatey** [comment]
Yep, i don't have permissions to move so wil recreate
