### ISSUE TITLE
Incorrect command on AWS LoadBalancer Controller page

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#558]
### Short description

The command to view a newly created ingress is incorrect. This is on page AWS LoadBalancer Controller - https://developer.lightbend.com/docs/akka-platform-guide/deployment/aws-ingress.html

### Details

The command on the page:
kubectl get ingress shopping-order-service-grpc-in

When creating an ingress for the shopping-cart-service the command that works is:
kubectl get ingress shopping-cart-service-grpc-ingress

**Comment by patriknw** [comment]
good catch, we renamed that
