### ISSUE TITLE
Troubleshooting shows "Reconciliation" states without further explanation

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-platform-guide#579]
Just noticed that when following a link from a release announcement.

https://developer.lightbend.com/docs/akka-platform-guide/deployment/troubleshooting.html

show "reconciliation" events with descriptions like "The reconciliation of a Microservice has completed successfully.":

![image](https://user-images.githubusercontent.com/9868/107952119-a2fb7500-6f99-11eb-958b-8e9531950ad6.png)

The concept of reconciliation isn't used somewhere else in the documentation. It's unclear to me if "reconciliation" has a particular meaning or if that's just an example event type.

**Comment by thothmoses** [comment]
Clarify instructions #736
