### ISSUE TITLE
Part VI ItemPopularity Projection

### ISSUE THREAD

**Issue by staniopolis** [akka/akka-platform-guide#603]
**2 mistakes** in code examples provided on the tutorial web-page

Page -> https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/projection-query.html

**1.** File -> **ShoppingCartService.proto**

**WRONG**
```
message GetItemPopularityResponse {
    string itemId = 1;
    int64 popularityCount = 2; 
}
```
**RIGHT**
```
message GetItemPopularityResponse {
    string itemId = 1;
    int64 count = 2; 
}
```
**2.** File -> **create_user_tables.sql**

**WRONG**
```
CREATE TABLE IF NOT EXISTS public.item_popularity (
    itemid VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    count BIGINT NOT NULL,
    PRIMARY KEY (itemid));
```

**RIGHT**
```
CREATE TABLE IF NOT EXISTS public.item_popularity (
    itemid VARCHAR(255) NOT NULL,
    count BIGINT NOT NULL,
    PRIMARY KEY (itemid));
```

**Comment by ignasi35** [comment]
refs #604 and #605

Both PR's were closed with some comments. I think both concerns listed in this issue were discussed. I will close this for the time being. Feel free to open again.
