### ISSUE TITLE
Tutorial source code download

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#61]
Even though the tutorial will be thorough and include all source code I think we should provide a download of the full source code for each part. I'm thinking that a zip file with different directories for each part would be nice.

**Comment by ennru** [comment]
The packager for this could possibly filter out the tags used for documentation snippets.

**Comment by ignasi35** [comment]
> The packager for this could possibly filter out the tags used for documentation snippets.

Why? We don't do such filtering on any other sample/docs we have. There are some `.g8` templates that include `// # some-tag` comments around the code. Are antora tags more verbose/annoying?

**Comment by patriknw** [comment]
Itt's not too bad, but can be somewhat confusing for users, so nice to filter.

```
// tag::events[]
...
// end::events[]
```

**Comment by patriknw** [comment]
Each step should describe in the beginning that the starting point is the codebase as presented in the previous step, or link to download the zip of previous step.

Before Running in each step we should also have a link to the download in case they failed to follow the instructions (or just not want to).

**Comment by octonato** [comment]
This is done for Scala, but keeping this open since we need for java as well

**Comment by octonato** [comment]
For the record:

I noticed that the tags are not being removed. The sed command we are using is bogus, at least in Mac. 

If it's working on travis, it's fine and we should not spent time on it.

**Comment by patriknw** [comment]
I think it works on Travis
