### ISSUE TITLE
Structure of top index page

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#633]
I see that "Key Information for Akka Cloud Platform on AWS" has been added to [top index page](https://developer.lightbend.com/docs/akka-platform-guide/index.html) at a strange location. I suggest that it should be after the Cloud deployment section on that page, resulting in headings:
* How to get the most out of this guide
* Akka Microservices tutorial
* Cloud deployment
* Key Information for Akka Cloud Platform on AWS
* How to…​

@thothmoses I guess you will touch the top page and then consider this proposal.

**Comment by thothmoses** [comment]
It will be revised - and eventually pulled to a different page. That placement is a bit odd, but we wanted it above the fold for the AWS FTR.
