### ISSUE TITLE
Missing copy button in Run Docker and Docker Compose section

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#634]
### Short description

Copy button not visible 

### Details

On page https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/template.html
3. Run Docker and Docker Compose
1. From the root project directory, run the following command:
docker-compose up -d

No copy button shown

**Comment by rstento** [comment]
The markup on the command needs to be changed, assigning to @thothmoses.

**Comment by thothmoses** [comment]
This is a quick fix. I was on that page for other changes in the reorg PR so I'll integrate it there.
