### ISSUE TITLE
Style of writing

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#65]
A question for Ruth.

In the tutorial I wanted to encourage the reader to actively build up the application by adding code themselves, even if that only means copy paste from the documentation snippets.

I used instructions like like "Add class ...", "You need to define...", "You implement the...", "Let's add...". followed by code snippet.

I don't know if that is a good style to use, or if it should be more indirect and describing like "This implements the..." followed by code snippet.

**Comment by ignasi35** [comment]
cc @rstento

**Comment by chbatey** [comment]
On a similar note I was reading this technical writing course recently and had some thoughts about our docs:
* Stop using the passive tense
* Shorter sentences
* More lists

**Comment by rstento** [comment]
These are good TW principles @Christopher Batey
<christopher.batey@lightbend.com>, along with lists, I might add that using
ordered (numbered lists) with any type of process/procedure helps the
reader keep track of where they are.


Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by patriknw** [comment]
I think this issue has served its purpose
