### ISSUE TITLE
2nd review on the main page (content order)

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#656]
I think the body also has a strange ordering. It keeps going back and forth on the various sections of the guide:

<img width="1638" alt="Screenshot_2021-03-26_at_08_41_45" src="https://user-images.githubusercontent.com/762126/112599020-a7744280-8e0f-11eb-80b8-0c4bce623d84.png">

(off topic) There's also a mention to  which is a name we dropped long ago in favor of other names. It'd be great if the first page had mode link to actual contents but I understand this PR is focused on the order of the contents.

_Originally posted by @ignasi35 in https://github.com/akka/akka-platform-guide/pull/648#discussion_r602074172_

**Comment by rstento** [comment]
> I think the body also has a strange ordering. It keeps going back and forth on the various sections of the guide:
> 
> <img alt="Screenshot_2021-03-26_at_08_41_45" width="1638" src="https://user-images.githubusercontent.com/762126/112599020-a7744280-8e0f-11eb-80b8-0c4bce623d84.png">
> 
> (off topic) There's also a mention to which is a name we dropped long ago in favor of other names. It'd be great if the first page had mode link to actual contents but I understand this PR is focused on the order of the contents.
> 
> _Originally posted by @ignasi35 in [#648 (comment)](https://github.com/akka/akka-platform-guide/pull/648#discussion_r602074172)_

@ignasi35 I think it is a good thing that the intro presents topics in a different order than the TOC. The TOC is ordered assuming that the majority of the audience will want to jump in and start the tutorial first. That may be true of the majority, but not be true for all. For the remaining readers, this page orients them and allows them to choose their own path through the doc. In addition for those who do just want to jump in and try the tutorial, it gives them a logical overview that will help them start creating the right mental model.

**Comment by thothmoses** [comment]
The ordering is intentional here. It is especially important that anyone going through the tutorial with cloud deployment have familiarity with the various cloud deployment components. But good catch on the 'Concepts' naming. I'll edit that and link.
