### ISSUE TITLE
External links without the arrow icon

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#665]
Links to dockerhub and quay-io in https://developer.lightbend.com/docs/akka-platform-guide/deployment/deploy.html should be marked as external links.

It may be about time we automated this detection.

**Comment by ignasi35** [comment]
More: in https://developer.lightbend.com/docs/akka-platform-guide/deployment/gcp-sql.html, the following text also has 2 external links:

> For production consider using the Cloud SQL proxy and IAM database authentication. Direct connectivity between GKE and Cloud SQL via private IP is only possible if using a Native VPC cluster otherwise the CLoud SQL proxy is required.

**Comment by thothmoses** [comment]
Closed with pr 667
