### ISSUE TITLE
Small change to the Shopping Cart example architecture diagram

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#688]
### Short description

It would be helpful to show the request/response flow in the Shopping Cart Microservice. 

### Details

The diagram has arrows going into and out of the Cart Service. These are request/response I/Os. It would be good if these 3 arrows had arrowheads on both ends. Or two arrows flowing in opposite directions to represent the I/O flow. 

I know this is a small tweak. But this came up when I was reviewing the diagram. The question was - why is the arrow only pointing in one direction?

https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/overview.html

**Comment by patriknw** [comment]
I create the diagram, and this is my thinking. I know arrows can be interpreted in various ways.

gRPC request from the outside to the CartService. Arrow to the CartService.

CartService sends a message to the CartEntity. Yes, it's a ask and there is a reply back, but the arrow indicates who initiated the interaction.

CartEntity writes events to the journal. Arrow to journal.

PopularityProjection reads events from the journal. Arrow from journal to projection. 

PopularityProjection writes to the query db. Arrow to query db.

and so on

**Comment by thothmoses** [comment]
@patriknw @mckeeh3  I am working on revisions of those graphics. I think appending text which illuminates Patrick's intention should clarify the image, keep it clean, and retain the flow that it demonstrates. Please see attached.
[example-overview.svg.zip](https://github.com/akka/akka-platform-guide/files/6367206/example-overview.svg.zip)
