### ISSUE TITLE
Wrong label on graphic

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#702]
In https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/overview.html

Architecture diagram in the Akka Platform Guide labels the shopping cart service as "Shopping Order Service".

**Comment by mckeeh3** [comment]
The label should be "Shopping Cart Service". 

Also, there is an arrow from the Send Order Projection to the Cart Entity. There is no direct interaction between those 2 things in any of the processing flows.

**Comment by mckeeh3** [comment]
Disregard my comment about the arrow. The arrow is correct, there is a reference from the projection handler to the entity in the example code.

**Comment by marcospereira** [comment]
Fixed by #707.
