### ISSUE TITLE
in How to use Cassandra instead of PostgreSQL section, full download link comes back with 404

### ISSUE THREAD

**Issue by dantodor** [akka/akka-platform-guide#705]
I think the bug description is clear enough.

**Comment by ignasi35** [comment]
Thanks for the heads up!
I've confirmed that _both_ java and scala links in https://developer.lightbend.com/docs/akka-platform-guide/how-to/cassandra-alternative.html#_source_downloads lead to 404. We'll look into it.

**Comment by ignasi35** [comment]
I suspect this was a one-time error on the deployment script that takes this guide and publishes it to dev.lb.com. I'll retrigger the build.

**Comment by thothmoses** [comment]
@ignasi35 For some reason these are still broken on the live doc - I tried it locally and there was no problem - but looking at the online repo it looks like the 'attachments' folder is being stripped out - present locally but not on Main or Current. IIt is listed in the gitignore file  with a note that implies these zip files are generated? Some guidance, please.

**Comment by thothmoses** [comment]
@adriaanm Since Ignasi is out could you take a look at this?

**Comment by patriknw** [comment]
I agree that this is important to look into. Could it even be that the other sample zip files are outdated (not updated any more) and we serve something old from the doc site?
cc @RayRoestenburg

**Comment by RayRoestenburg** [comment]
I'll have a look. worked locally for me as well, on mac you need to use gnu-sed (https://gist.github.com/andre3k1/e3a1a7133fded5de5a9ee99c87c6fa0d#gistcomment-3524266).

**Comment by RayRoestenburg** [comment]
I think I see what is happening, the zips are ending up in the wrong directory in the published tar ball:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/156425/121562718-01050a00-ca1a-11eb-85d7-d5cd8b5ad9a6.png">
@ignasi35 @patriknw

**Comment by thothmoses** [comment]
@patriknw @RayRoestenburg Yep, it should be under how 'how-to' How do we fix that?
