### ISSUE TITLE
Add link to the APG 5-part workshop series

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#730]
### Short description

Add a sentence to the opening section of the ACP that points to the 5-part ACP workshop.

### Details

In the first section of the [Akka Platform Guide](https://developer.lightbend.com/docs/akka-platform-guide/index.html), the second paragraph, add a sentence about the ACP workshop.

Akka Platform is a toolkit for building highly concurrent systems that are scalable, highly efficient, and resilient by using Reactive Principles. The Akka Platform includes support for Akka, additional commercial components, and is available from Lightbend as a [subscription](https://www.lightbend.com/lightbend-subscription). You can check out our [five-part Akka Platform workshop for developers](https://info.lightbend.com/akka-platform-workshop-five-parts-on-demand-register.html) for a guided, hands-on walkthrough of Akka Platform.

Submitting this request for Oliver.

**Comment by thothmoses** [comment]
@mckeeh3 added via https://github.com/akka/akka-platform-guide/pull/731
Sorry I didn't get to this earlier.
