### ISSUE TITLE
Use of bootstrap and discovery

### ISSUE THREAD

**Issue by chbatey** [akka/akka-platform-guide#79]
Bootstrap - should we use it locally too so we don't end up having to describe seed nodes and bootstrap. Also avoids not having bootstrap.start being conditional for local.

Discovery - consider not using it for Kafka/gRPC/Cassandra. In k8s these can be headless services and for local we can override them to be localhost with config.

**Comment by patriknw** [comment]
Bootstrap was added in https://github.com/akka/akka-platform-guide/pull/81
