### ISSUE TITLE
Tutorial navigation

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#91]
I don't know if we will get navigation for free with the real style. Otherwise we need to add links to next step at the the end of the tutorial pages.

**Comment by patriknw** [comment]
Let's add this. We can have 'Learn more' section at the end of each with link to next (and prev) and a few related links to reference docs

**Comment by patriknw** [comment]
@ignasi35 said:

> Having automatic Prev/Next would be great. Adding a custom admonition (https://asciidoctor.org/docs/user-manual/#admonition) for related topics would be ideal.

**Comment by ignasi35** [comment]
I don't know much about custom admonitions but maybe we can use a [custom icon](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-admonition-icon) using the [fa-books](https://fontawesome.com/icons/books?style=duotone). 

`📚 Learn  more: ...`

**Comment by patriknw** [comment]
I'll add something, and we can revisit the stylish solution later.

**Comment by ignasi35** [comment]
for the record: https://gitlab.com/antora/antora-ui-default/-/blob/master/src/partials/pagination.hbs
