### ISSUE TITLE
Create g8 template for empty project

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#96]
It will be the starting point for the tutorial and contains:
* build with dependencies and gRPC plugin
* configuration
* empty Main class

Until we have this in place the docs-source/docs/modules/shopping-microservices/examples/empty-shopping-cart-service-scala in branch `wip-empty-project-patriknw` can be used. https://github.com/akka/akka-platform-guide/tree/wip-empty-project-patriknw/docs-source/docs/modules/shopping-microservices/examples/empty-shopping-cart-service-scala

**Comment by ignasi35** [comment]
Maybe we can write the tutorial using the `akka-grpc-quickstart-scala.g8`? 
This way users get familiar with already existing solutions and we decrease maintainability.

**Comment by patriknw** [comment]
> Maybe we can write the tutorial using the akka-grpc-quickstart-scala.g8?

I think it's better to have a specific seed for Akka Microservices to include the right dependencies and configuration.

**Comment by ignasi35** [comment]
> I think it's better to have a specific seed for Akka Microservices to include the right dependencies and configuration.

Hmmm, I think we're talking about different things, then. I Agre the two following templates would be useful:

1. a `.g8` template with the minimum dependenciess required for step 01 on the tutorial. I think the `akka-grpc-quickstart-scala.g8` fills that need.
2. a `.g8` template to build a new Akka Microsevices (includes gRPC, cluster, jackson, projections,...).

**Comment by patriknw** [comment]
My intention is that step 01 is still a new microservice. The seed would come with batteries included when it comes to dependencies and configuration so that the developer can focus on coding. Then we would have an (optional) how-to that describes how build dependencies can be removed, ticket #51, if not needed.
