### ISSUE TITLE
Review/unify look of images

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#97]
Images in some of the `Concepts` pages e.g. https://github.com/akka/akka-platform-guide/blob/main/docs-source/docs/modules/concepts/assets/images/concepts/internal-and-external-communication.png) were directly copy/pasted from the original location. 

As a consequence, the look of images in https://github.com/akka/akka-platform-guide/tree/main/docs-source/docs/modules/concepts/assets/images varyies or doesn't fully match the text (as it evolved).

**Comment by thothmoses** [comment]
these have been updated and standardized, and brought into line with the Lightbend color palette. per Updated some graphics with reflow and conversion to SVG #687
